name: tax calculator app

services:
  service-a:
    build: ./service-a
    image: service-a
    container_name: service-a

    ports:
      - "3000:3000"

    depends_on:
      - service-b

    env_file:
      - ./service-a/.env

    networks:
      - tax-container

  service-b:
    build: ./service-b
    image: service-b
    container_name: service-b

    ports:
      - "4000:4000"
    networks:
      - tax-container

  service-c:
    build: ./service-c
    image: service-c
    container_name: service-c

    ports:
      - "5173:80"

    # env_file:
    #   - ./service-c/.env
    environment:
      - VITE_API_URL=http://localhost:3000

    depends_on:
      - service-a

    networks:
      - tax-container

networks:
  tax-container:
    driver: bridge
